// Generated by CoffeeScript 1.8.0
(function() {
  var apiRoutes;

  apiRoutes = function(app) {
    return app.get('/api/student_profile', function(req, res) {
      var profile;
      profile = req.user;
      return res.status(200).json(profile);
    });
  };

  module.exports = apiRoutes;

}).call(this);

//# sourceMappingURL=api.js.map
