// Generated by CoffeeScript 1.8.0
(function() {
  var mysql;

  mysql = require('mysql');

  module.exports = {
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'Omni'
  };

}).call(this);

//# sourceMappingURL=conn.js.map
