// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(req, profileCallback) {
    var conn, connection, mysql, profile, q, query;
    conn = require('./conn');
    mysql = require('mysql');
    profile = {};
    connection = mysql.createConnection(conn);
    q = "select * from student_details where usn = '" + req.usn + "'";
    console.log(q);
    return query = connection.query(q, function(err, rows) {
      if (err) {
        console.log(err);
      }
      return profileCallback(rows[0]);
    });
  };

}).call(this);

//# sourceMappingURL=student_prof.js.map
